# Generated by Django 3.2.5 on 2021-07-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swahili', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swahilicategory',
            name='author',
        ),
        migrations.RemoveField(
            model_name='swahilisubcategory',
            name='author',
        ),
    ]
